site_name: Dynamic Mapping Benchmark
site_author: Qingwen Zhang

# Repository
repo_name: KTH-RPL/DynamicMap_Benchmark
repo_url: https://github.com/KTH-RPL/DynamicMap_Benchmark
edit_uri: ./edit/mkdocs/docs

# Copyright
copyright: Copyright &copy; 2023 - 2024 KTH RPL Qingwen Zhang

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  # favicon: 📖
  icon:
    logo: logo



# Plugins
plugins:
  - git-committers:
      repository: KTH-RPL/DynamicMap_Benchmark
      branch: mkdocs
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
  # - git-authors
  - mkdocs-video:
      is_video: true
      video_muted: true
      video_autoplay: true
      css_style:
        width: "100%"
# Hooks
hooks:
  - material/.overrides/hooks/translations.py

# Customization
extra:
  # annotate:
    # json: [.s2]
  # analytics:
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KTH-RPL
    - icon: fontawesome/brands/gitter
      link: https://www.kth.se/is/rpl

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Getting started: 
    - Home: index.md
    - Data: 
      - Data Overview: data/index.md
      - Data Creation: data/creation.md
    - Method: 
      - Overview: method/index.md
      # - DUFOMap: method/dufomap.md
    - Evaluation: 
      - Overview: evaluation/index.md
    - Project Lists: papers.md